//! Semantic regression families and explicit shared synthetic fixtures.

mod artifact_hydration_preflight;
mod capture_artifact_storage;
mod capture_identity;
mod capture_w30_audition;
mod commit_pipeline_order;
mod dawproject_xml_schema;
mod export_receipt_daw_preflight;
mod export_receipt_hydration_preflight;
mod export_receipt_stem_package_preflight;
mod feral_support_runtime_controls;
mod fixture_regressions_tr909_slam;
mod fixtures;
mod ghost_assist_queue;
mod graph_transaction;
mod live_source_timing;
mod mc202_queue_timing;
mod mc202_restore_replay;
mod mc202_source_phrase_articulation;
mod mc202_source_phrase_candidate_families;
mod mc202_source_phrase_feature_rejections;
mod mc202_source_phrase_pressure_contours;
mod mc202_source_phrase_production_scoring;
mod mc202_source_phrase_quality_gates;
mod p016_daw_session_audible_output_action;
mod p016_daw_session_export_action;
mod p016_daw_session_host_import_action;
mod p016_live_master_dawproject;
mod p016_live_master_recording;
mod p016_live_recording_export_action;
mod p016_product_export_action;
mod p016_w30_hook_dawproject_action;
mod persistence_runtime_view;
mod recovery_choice_dry_run;
mod recovery_hydration_guidance;
mod recovery_payload_guidance;
mod recovery_replay_family_diagnostics;
mod recovery_surface;
mod replay_hardening;
mod restore_contracts;
mod restore_history;
mod scene_chain_transition_proof;
mod scene_fixture_regression;
mod scene_replay;
mod scene_restore_mc202_queue_start;
mod scene_source_identity;
mod snapshot_payload_restore_failures;
#[cfg(unix)]
mod source_file_admission;
mod source_ingest_identity;
mod source_map_navigation;
mod source_monitor_scene_reposition;
mod source_ref_profile;
mod source_timing_consumer_readiness;
mod source_timing_runtime_view;
mod source_transport_restore;
mod stage_style_snapshot_convergence;
mod tr909_policy_undo_ingest;
mod tr909_replay;
mod tr909_takeover_source_support;
mod transport_scene_select;
mod w30_backfill_mc202_commits;
mod w30_capture_bar_group_replay;
mod w30_capture_loop_replay;
mod w30_capture_now_replay;
mod w30_capture_to_pad_replay;
mod w30_committed_bank_damage;
mod w30_committed_preview;
mod w30_committed_resample;
mod w30_feral_rebake_policy;
mod w30_loop_freeze_artifact_replay;
mod w30_queue_conflicts_live_recall;
mod w30_queue_core;
mod w30_replay_core;
mod w30_replay_snapshot_variants;
mod w30_resample_artifact_replay;
mod w30_resample_promotion_replay;
mod w30_source_window_artifacts;
mod w30_source_window_projection;

// Preserve the four existing crate-internal synthetic-fixture entrypoints.
pub(crate) use fixtures::session_source::{sample_graph, sample_session};
pub(crate) use p016_product_export_action::{
    w30_hook_export_state, write_source_matched_handoff_fixture,
};
