"""Shared suite-report acceptance policy, not runtime gain or a taste verdict.

Values are unchanged from the V1 generator/validator pair (RIOTBOX-1420).
Floors and ceilings are inclusive. Their diagnostic provenance and change rules
are recorded in docs/engineering/audio_numeric_inventory_2026-09-22.md.
Family-specific gates stay with their existing validator owners.
"""

MIN_FERAL_SUPPORT_GENERATED_TO_SOURCE_RMS_RATIO = 0.145
MAX_FERAL_SOURCE_FIRST_GENERATED_TO_SOURCE_RMS_RATIO = 0.08
MIN_FERAL_SOURCE_FIRST_MASKING_HEADROOM = 0.04
MAX_FERAL_SUPPORT_GENERATED_TO_SOURCE_RMS_RATIO = 0.46
MIN_FERAL_TR909_RENDERED_SUPPORT_CONTRIBUTION_RATIO = 0.050
MIN_FERAL_TR909_RENDERED_LOW_BAND_RMS = 0.0030
MIN_SOURCE_CHARACTER_WINDOW_RMS_RETENTION_RATIO = 0.98
MIN_SOURCE_CHARACTER_WINDOW_SEARCHED_CASE_COUNT = 3
MIN_SOURCE_CHARACTER_WINDOW_PROMOTED_CASE_COUNT = 1
MIN_SOURCE_SELECTION_POLICY_CANDIDATES = 3
MIN_SOURCE_SELECTION_RMS_RETENTION_RATIO = 0.60
MIN_SOURCE_SELECTION_SCORE_LIFT = 0.0
