[package]
name = "riotbox-audio"
version.workspace = true
edition.workspace = true
license-file.workspace = true

[features]
limiter-calibration = []

[dependencies]
arc-swap = "1.7"
cpal = "0.17.3"
riotbox-core = { path = "../riotbox-core" }
same-file = "1.0.6"
serde.workspace = true
serde_json.workspace = true
sha2.workspace = true

[target.'cfg(unix)'.dependencies]
libc.workspace = true

[dev-dependencies]
tempfile.workspace = true
